"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

import nulltype  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from openapi_client.model.community_context import CommunityContext
    from openapi_client.model.list_community_roles import ListCommunityRoles
    globals()['CommunityContext'] = CommunityContext
    globals()['ListCommunityRoles'] = ListCommunityRoles


class Community(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (int,),  # noqa: E501
            'about': (str,),  # noqa: E501
            'avatar_url': (str,),  # noqa: E501
            'context': (CommunityContext,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'flag_text': (str,),  # noqa: E501
            'is_nsfw': (bool,),  # noqa: E501
            'lang': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'num_authors': (int,),  # noqa: E501
            'num_pending': (int,),  # noqa: E501
            'settings': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
            'subscribers': (int,),  # noqa: E501
            'sum_pending': (int,),  # noqa: E501
            'team': (ListCommunityRoles,),  # noqa: E501
            'title': (str,),  # noqa: E501
            'type_id': (int,),  # noqa: E501
            'admins': ([str],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'about': 'about',  # noqa: E501
        'avatar_url': 'avatar_url',  # noqa: E501
        'context': 'context',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'flag_text': 'flag_text',  # noqa: E501
        'is_nsfw': 'is_nsfw',  # noqa: E501
        'lang': 'lang',  # noqa: E501
        'name': 'name',  # noqa: E501
        'num_authors': 'num_authors',  # noqa: E501
        'num_pending': 'num_pending',  # noqa: E501
        'settings': 'settings',  # noqa: E501
        'subscribers': 'subscribers',  # noqa: E501
        'sum_pending': 'sum_pending',  # noqa: E501
        'team': 'team',  # noqa: E501
        'title': 'title',  # noqa: E501
        'type_id': 'type_id',  # noqa: E501
        'admins': 'admins',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, id, about, avatar_url, context, created_at, flag_text, is_nsfw, lang, name, num_authors, num_pending, settings, subscribers, sum_pending, team, title, type_id, *args, **kwargs):  # noqa: E501
        """Community - a model defined in OpenAPI

        Args:
            id (int):
            about (str):
            avatar_url (str):
            context (CommunityContext):
            created_at (datetime):
            flag_text (str):
            is_nsfw (bool):
            lang (str):
            name (str):
            num_authors (int):
            num_pending (int):
            settings ({str: (bool, date, datetime, dict, float, int, list, str, none_type)}):
            subscribers (int):
            sum_pending (int):
            team (ListCommunityRoles):
            title (str):
            type_id (int):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            admins ([str]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        self.about = about
        self.avatar_url = avatar_url
        self.context = context
        self.created_at = created_at
        self.flag_text = flag_text
        self.is_nsfw = is_nsfw
        self.lang = lang
        self.name = name
        self.num_authors = num_authors
        self.num_pending = num_pending
        self.settings = settings
        self.subscribers = subscribers
        self.sum_pending = sum_pending
        self.team = team
        self.title = title
        self.type_id = type_id
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
