"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

import nulltype  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class GetRankedPostsRequestParams(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('sort',): {
            'TRENDING': "trending",
            'HOT': "hot",
            'CREATED': "created",
            'PROMOTED': "promoted",
            'PAYOUT': "payout",
            'PAYOUT_COMMENTS': "payout_comments",
            'MUTED': "muted",
        },
    }

    validations = {
        ('limit',): {
            'inclusive_maximum': 100,
            'inclusive_minimum': 1,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'sort': (str,),  # noqa: E501
            'start_author': (str,),  # noqa: E501
            'start_permlink': (str,),  # noqa: E501
            'limit': (int,),  # noqa: E501
            'tag': (str,),  # noqa: E501
            'observer': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'sort': 'sort',  # noqa: E501
        'start_author': 'start_author',  # noqa: E501
        'start_permlink': 'start_permlink',  # noqa: E501
        'limit': 'limit',  # noqa: E501
        'tag': 'tag',  # noqa: E501
        'observer': 'observer',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, sort, *args, **kwargs):  # noqa: E501
        """GetRankedPostsRequestParams - a model defined in OpenAPI

        Args:
            sort (str): ### Sort order: trending - [if tag is community pinned posts first], top posts with highest trending score first; paging cuts out given and more trending posts hot - top posts from blogs of accounts that given account is following ranked by creation/reblog time, not older than last month   created - [if tag is community pinned posts first], newest top posts first (grayed out not considered); paging cuts out given and newer posts promoted - promoted posts with highest promotion fund first; paging cuts out given and more promoted posts payout - only posts that will cashout between 12 and 36 hours from head block are considered, posts with higher pending payout first; paging cuts out given and higher payout posts payout_comments - only replies are considered, posts with higher pending payout first; paging cuts out given and higher payout posts muted - grayed out posts that are to receive nonzero payout are considered, posts with higher pending payout first; paging cuts out given and higher payout posts 

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            start_author (str): author account name, if passed must be passed with start_permlink. [optional]  # noqa: E501
            start_permlink (str): post permlink of given author, point to valid post, paging mechanism. [optional]  # noqa: E501
            limit (int): [optional] if omitted the server will use the default value of 20  # noqa: E501
            tag (str): my (with observer) - turns on filtering for posts within communities subscribed to by observer all - same as default none/blank hive-{number} - has to point to valid community; turns on filtering for posts within given community {tag} - has to point to valid tag; turns on filtering for posts with given tag (given category in case of 'payout' and 'payout_comments') . [optional]  # noqa: E501
            observer (str): mandatory for \"my\" tag, points to valid account; when given supplements blacklists stats in posts and filters out posts of muted authors (with exception of \"muted\" sort). [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.sort = sort
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
