[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools == 63.1.0',
    'wheel == 0.37.1',
    'gitpython == 3.1.27',
]


[tool.black]
line-length = 120
skip-string-normalization = true
