"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_pop_communites_request_params import ListPopCommunitesRequestParams
globals()['ListPopCommunitesRequestParams'] = ListPopCommunitesRequestParams
from openapi_client.model.list_pop_communites_request import ListPopCommunitesRequest


class TestListPopCommunitesRequest(unittest.TestCase):
    """ListPopCommunitesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPopCommunitesRequest(self):
        """Test ListPopCommunitesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListPopCommunitesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
