"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_payout_stats_request_params import GetPayoutStatsRequestParams
globals()['GetPayoutStatsRequestParams'] = GetPayoutStatsRequestParams
from openapi_client.model.get_payout_stats_request import GetPayoutStatsRequest


class TestGetPayoutStatsRequest(unittest.TestCase):
    """GetPayoutStatsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPayoutStatsRequest(self):
        """Test GetPayoutStatsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPayoutStatsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
