"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.discussion import Discussion
globals()['Discussion'] = Discussion
from openapi_client.model.get_ranked_posts import GetRankedPosts


class TestGetRankedPosts(unittest.TestCase):
    """GetRankedPosts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetRankedPosts(self):
        """Test GetRankedPosts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetRankedPosts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
