"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_account_posts_request_params import GetAccountPostsRequestParams
globals()['GetAccountPostsRequestParams'] = GetAccountPostsRequestParams
from openapi_client.model.get_account_posts_request import GetAccountPostsRequest


class TestGetAccountPostsRequest(unittest.TestCase):
    """GetAccountPostsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAccountPostsRequest(self):
        """Test GetAccountPostsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAccountPostsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
