"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.active_votes import ActiveVotes
from openapi_client.model.beneficiares import Beneficiares
from openapi_client.model.get_post_stats import GetPostStats
globals()['ActiveVotes'] = ActiveVotes
globals()['Beneficiares'] = Beneficiares
globals()['GetPostStats'] = GetPostStats
from openapi_client.model.discussion import Discussion


class TestDiscussion(unittest.TestCase):
    """Discussion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiscussion(self):
        """Test Discussion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Discussion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
