"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_profile_request_params import GetProfileRequestParams
globals()['GetProfileRequestParams'] = GetProfileRequestParams
from openapi_client.model.get_profile_request import GetProfileRequest


class TestGetProfileRequest(unittest.TestCase):
    """GetProfileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetProfileRequest(self):
        """Test GetProfileRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetProfileRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
