"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_discussion_request_params import GetDiscussionRequestParams
globals()['GetDiscussionRequestParams'] = GetDiscussionRequestParams
from openapi_client.model.get_discussion_request import GetDiscussionRequest


class TestGetDiscussionRequest(unittest.TestCase):
    """GetDiscussionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDiscussionRequest(self):
        """Test GetDiscussionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetDiscussionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
