"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_ranked_posts_request_params import GetRankedPostsRequestParams


class TestGetRankedPostsRequestParams(unittest.TestCase):
    """GetRankedPostsRequestParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetRankedPostsRequestParams(self):
        """Test GetRankedPostsRequestParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetRankedPostsRequestParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
