"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_subscribers_request_params import ListSubscribersRequestParams
globals()['ListSubscribersRequestParams'] = ListSubscribersRequestParams
from openapi_client.model.list_subscribers_request import ListSubscribersRequest


class TestListSubscribersRequest(unittest.TestCase):
    """ListSubscribersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSubscribersRequest(self):
        """Test ListSubscribersRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListSubscribersRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
