"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_post_request_params import GetPostRequestParams
globals()['GetPostRequestParams'] = GetPostRequestParams
from openapi_client.model.get_post_request import GetPostRequest


class TestGetPostRequest(unittest.TestCase):
    """GetPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPostRequest(self):
        """Test GetPostRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPostRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
