"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_all_subscriptions import ListAllSubscriptions


class TestListAllSubscriptions(unittest.TestCase):
    """ListAllSubscriptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAllSubscriptions(self):
        """Test ListAllSubscriptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAllSubscriptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
