"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.community_context_request_params import CommunityContextRequestParams
globals()['CommunityContextRequestParams'] = CommunityContextRequestParams
from openapi_client.model.community_context_request import CommunityContextRequest


class TestCommunityContextRequest(unittest.TestCase):
    """CommunityContextRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommunityContextRequest(self):
        """Test CommunityContextRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommunityContextRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
