# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CommunityContextRequestParams(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, account=None):  # noqa: E501
        """CommunityContextRequestParams - a model defined in OpenAPI

        :param name: The name of this CommunityContextRequestParams.  # noqa: E501
        :type name: str
        :param account: The account of this CommunityContextRequestParams.  # noqa: E501
        :type account: str
        """
        self.openapi_types = {
            'name': str,
            'account': str
        }

        self.attribute_map = {
            'name': 'name',
            'account': 'account'
        }

        self._name = name
        self._account = account

    @classmethod
    def from_dict(cls, dikt) -> 'CommunityContextRequestParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommunityContextRequest_params of this CommunityContextRequestParams.  # noqa: E501
        :rtype: CommunityContextRequestParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this CommunityContextRequestParams.

        community name  # noqa: E501

        :return: The name of this CommunityContextRequestParams.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CommunityContextRequestParams.

        community name  # noqa: E501

        :param name: The name of this CommunityContextRequestParams.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def account(self):
        """Gets the account of this CommunityContextRequestParams.

        account name  # noqa: E501

        :return: The account of this CommunityContextRequestParams.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this CommunityContextRequestParams.

        account name  # noqa: E501

        :param account: The account of this CommunityContextRequestParams.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account
