# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CommunityRequestParams(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, observer=None):  # noqa: E501
        """CommunityRequestParams - a model defined in OpenAPI

        :param name: The name of this CommunityRequestParams.  # noqa: E501
        :type name: str
        :param observer: The observer of this CommunityRequestParams.  # noqa: E501
        :type observer: str
        """
        self.openapi_types = {
            'name': str,
            'observer': str
        }

        self.attribute_map = {
            'name': 'name',
            'observer': 'observer'
        }

        self._name = name
        self._observer = observer

    @classmethod
    def from_dict(cls, dikt) -> 'CommunityRequestParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommunityRequest_params of this CommunityRequestParams.  # noqa: E501
        :rtype: CommunityRequestParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this CommunityRequestParams.

        community name  # noqa: E501

        :return: The name of this CommunityRequestParams.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CommunityRequestParams.

        community name  # noqa: E501

        :param name: The name of this CommunityRequestParams.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def observer(self):
        """Gets the observer of this CommunityRequestParams.

        account name  # noqa: E501

        :return: The observer of this CommunityRequestParams.
        :rtype: str
        """
        return self._observer

    @observer.setter
    def observer(self, observer):
        """Sets the observer of this CommunityRequestParams.

        account name  # noqa: E501

        :param observer: The observer of this CommunityRequestParams.
        :type observer: str
        """

        self._observer = observer
