# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ErrorMessageError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None, data=None):  # noqa: E501
        """ErrorMessageError - a model defined in OpenAPI

        :param code: The code of this ErrorMessageError.  # noqa: E501
        :type code: str
        :param message: The message of this ErrorMessageError.  # noqa: E501
        :type message: str
        :param data: The data of this ErrorMessageError.  # noqa: E501
        :type data: str
        """
        self.openapi_types = {
            'code': str,
            'message': str,
            'data': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'data': 'data'
        }

        self._code = code
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorMessageError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorMessage_error of this ErrorMessageError.  # noqa: E501
        :rtype: ErrorMessageError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this ErrorMessageError.


        :return: The code of this ErrorMessageError.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorMessageError.


        :param code: The code of this ErrorMessageError.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self):
        """Gets the message of this ErrorMessageError.


        :return: The message of this ErrorMessageError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorMessageError.


        :param message: The message of this ErrorMessageError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def data(self):
        """Gets the data of this ErrorMessageError.


        :return: The data of this ErrorMessageError.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ErrorMessageError.


        :param data: The data of this ErrorMessageError.
        :type data: str
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
