# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GetProfileRequestParams(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, account=None, observer=None):  # noqa: E501
        """GetProfileRequestParams - a model defined in OpenAPI

        :param account: The account of this GetProfileRequestParams.  # noqa: E501
        :type account: str
        :param observer: The observer of this GetProfileRequestParams.  # noqa: E501
        :type observer: str
        """
        self.openapi_types = {
            'account': str,
            'observer': str
        }

        self.attribute_map = {
            'account': 'account',
            'observer': 'observer'
        }

        self._account = account
        self._observer = observer

    @classmethod
    def from_dict(cls, dikt) -> 'GetProfileRequestParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetProfileRequest_params of this GetProfileRequestParams.  # noqa: E501
        :rtype: GetProfileRequestParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account(self):
        """Gets the account of this GetProfileRequestParams.

        account name  # noqa: E501

        :return: The account of this GetProfileRequestParams.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this GetProfileRequestParams.

        account name  # noqa: E501

        :param account: The account of this GetProfileRequestParams.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def observer(self):
        """Gets the observer of this GetProfileRequestParams.

        account name of observer, used to add information about relationship of observer with given profile account  # noqa: E501

        :return: The observer of this GetProfileRequestParams.
        :rtype: str
        """
        return self._observer

    @observer.setter
    def observer(self, observer):
        """Sets the observer of this GetProfileRequestParams.

        account name of observer, used to add information about relationship of observer with given profile account  # noqa: E501

        :param observer: The observer of this GetProfileRequestParams.
        :type observer: str
        """

        self._observer = observer
