# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GetPayoutStatsRequestParams(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, limit=250):  # noqa: E501
        """GetPayoutStatsRequestParams - a model defined in OpenAPI

        :param limit: The limit of this GetPayoutStatsRequestParams.  # noqa: E501
        :type limit: int
        """
        self.openapi_types = {
            'limit': int
        }

        self.attribute_map = {
            'limit': 'limit'
        }

        self._limit = limit

    @classmethod
    def from_dict(cls, dikt) -> 'GetPayoutStatsRequestParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetPayoutStatsRequest_params of this GetPayoutStatsRequestParams.  # noqa: E501
        :rtype: GetPayoutStatsRequestParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def limit(self):
        """Gets the limit of this GetPayoutStatsRequestParams.


        :return: The limit of this GetPayoutStatsRequestParams.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this GetPayoutStatsRequestParams.


        :param limit: The limit of this GetPayoutStatsRequestParams.
        :type limit: int
        """
        if limit is not None and limit > 250:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value less than or equal to `250`")  # noqa: E501
        if limit is not None and limit < 1:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value greater than or equal to `1`")  # noqa: E501

        self._limit = limit
