# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GetPayoutStats(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, blogs=None, items=None, total=None):  # noqa: E501
        """GetPayoutStats - a model defined in OpenAPI

        :param blogs: The blogs of this GetPayoutStats.  # noqa: E501
        :type blogs: float
        :param items: The items of this GetPayoutStats.  # noqa: E501
        :type items: List[str]
        :param total: The total of this GetPayoutStats.  # noqa: E501
        :type total: float
        """
        self.openapi_types = {
            'blogs': float,
            'items': List[str],
            'total': float
        }

        self.attribute_map = {
            'blogs': 'blogs',
            'items': 'items',
            'total': 'total'
        }

        self._blogs = blogs
        self._items = items
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'GetPayoutStats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetPayoutStats of this GetPayoutStats.  # noqa: E501
        :rtype: GetPayoutStats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def blogs(self):
        """Gets the blogs of this GetPayoutStats.


        :return: The blogs of this GetPayoutStats.
        :rtype: float
        """
        return self._blogs

    @blogs.setter
    def blogs(self, blogs):
        """Sets the blogs of this GetPayoutStats.


        :param blogs: The blogs of this GetPayoutStats.
        :type blogs: float
        """
        if blogs is None:
            raise ValueError("Invalid value for `blogs`, must not be `None`")  # noqa: E501

        self._blogs = blogs

    @property
    def items(self):
        """Gets the items of this GetPayoutStats.


        :return: The items of this GetPayoutStats.
        :rtype: List[str]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this GetPayoutStats.


        :param items: The items of this GetPayoutStats.
        :type items: List[str]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items

    @property
    def total(self):
        """Gets the total of this GetPayoutStats.


        :return: The total of this GetPayoutStats.
        :rtype: float
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this GetPayoutStats.


        :param total: The total of this GetPayoutStats.
        :type total: float
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total
