# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ListPopCommunitesRequestParams(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, limit=25):  # noqa: E501
        """ListPopCommunitesRequestParams - a model defined in OpenAPI

        :param limit: The limit of this ListPopCommunitesRequestParams.  # noqa: E501
        :type limit: int
        """
        self.openapi_types = {
            'limit': int
        }

        self.attribute_map = {
            'limit': 'limit'
        }

        self._limit = limit

    @classmethod
    def from_dict(cls, dikt) -> 'ListPopCommunitesRequestParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListPopCommunitesRequest_params of this ListPopCommunitesRequestParams.  # noqa: E501
        :rtype: ListPopCommunitesRequestParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def limit(self):
        """Gets the limit of this ListPopCommunitesRequestParams.

        limit number of listed communities  # noqa: E501

        :return: The limit of this ListPopCommunitesRequestParams.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this ListPopCommunitesRequestParams.

        limit number of listed communities  # noqa: E501

        :param limit: The limit of this ListPopCommunitesRequestParams.
        :type limit: int
        """
        if limit is not None and limit > 25:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value less than or equal to `25`")  # noqa: E501
        if limit is not None and limit < 1:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value greater than or equal to `1`")  # noqa: E501

        self._limit = limit
