# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ListSubscribersRequestParams(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, community=None, last=None, limit=100):  # noqa: E501
        """ListSubscribersRequestParams - a model defined in OpenAPI

        :param community: The community of this ListSubscribersRequestParams.  # noqa: E501
        :type community: str
        :param last: The last of this ListSubscribersRequestParams.  # noqa: E501
        :type last: str
        :param limit: The limit of this ListSubscribersRequestParams.  # noqa: E501
        :type limit: int
        """
        self.openapi_types = {
            'community': str,
            'last': str,
            'limit': int
        }

        self.attribute_map = {
            'community': 'community',
            'last': 'last',
            'limit': 'limit'
        }

        self._community = community
        self._last = last
        self._limit = limit

    @classmethod
    def from_dict(cls, dikt) -> 'ListSubscribersRequestParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListSubscribersRequest_params of this ListSubscribersRequestParams.  # noqa: E501
        :rtype: ListSubscribersRequestParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def community(self):
        """Gets the community of this ListSubscribersRequestParams.

        community name  # noqa: E501

        :return: The community of this ListSubscribersRequestParams.
        :rtype: str
        """
        return self._community

    @community.setter
    def community(self, community):
        """Sets the community of this ListSubscribersRequestParams.

        community name  # noqa: E501

        :param community: The community of this ListSubscribersRequestParams.
        :type community: str
        """
        if community is None:
            raise ValueError("Invalid value for `community`, must not be `None`")  # noqa: E501

        self._community = community

    @property
    def last(self):
        """Gets the last of this ListSubscribersRequestParams.

         name of subscriber; paging mechanism (cuts out this and \"higher\" subscribers, depends on created at desc)  # noqa: E501

        :return: The last of this ListSubscribersRequestParams.
        :rtype: str
        """
        return self._last

    @last.setter
    def last(self, last):
        """Sets the last of this ListSubscribersRequestParams.

         name of subscriber; paging mechanism (cuts out this and \"higher\" subscribers, depends on created at desc)  # noqa: E501

        :param last: The last of this ListSubscribersRequestParams.
        :type last: str
        """

        self._last = last

    @property
    def limit(self):
        """Gets the limit of this ListSubscribersRequestParams.

        limit number of listed subscribers  # noqa: E501

        :return: The limit of this ListSubscribersRequestParams.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this ListSubscribersRequestParams.

        limit number of listed subscribers  # noqa: E501

        :param limit: The limit of this ListSubscribersRequestParams.
        :type limit: int
        """
        if limit is not None and limit > 100:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value less than or equal to `100`")  # noqa: E501
        if limit is not None and limit < 1:  # noqa: E501
            raise ValueError("Invalid value for `limit`, must be a value greater than or equal to `1`")  # noqa: E501

        self._limit = limit
