# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.profile_metadata_profile import ProfileMetadataProfile
from openapi_server import util

from openapi_server.models.profile_metadata_profile import ProfileMetadataProfile  # noqa: E501

class ProfileMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, profile=None):  # noqa: E501
        """ProfileMetadata - a model defined in OpenAPI

        :param profile: The profile of this ProfileMetadata.  # noqa: E501
        :type profile: ProfileMetadataProfile
        """
        self.openapi_types = {
            'profile': ProfileMetadataProfile
        }

        self.attribute_map = {
            'profile': 'profile'
        }

        self._profile = profile

    @classmethod
    def from_dict(cls, dikt) -> 'ProfileMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Profile_metadata of this ProfileMetadata.  # noqa: E501
        :rtype: ProfileMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def profile(self):
        """Gets the profile of this ProfileMetadata.


        :return: The profile of this ProfileMetadata.
        :rtype: ProfileMetadataProfile
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """Sets the profile of this ProfileMetadata.


        :param profile: The profile of this ProfileMetadata.
        :type profile: ProfileMetadataProfile
        """
        if profile is None:
            raise ValueError("Invalid value for `profile`, must not be `None`")  # noqa: E501

        self._profile = profile
