"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_community_roles_request_params import ListCommunityRolesRequestParams
globals()['ListCommunityRolesRequestParams'] = ListCommunityRolesRequestParams
from openapi_client.model.list_community_roles_request import ListCommunityRolesRequest


class TestListCommunityRolesRequest(unittest.TestCase):
    """ListCommunityRolesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListCommunityRolesRequest(self):
        """Test ListCommunityRolesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListCommunityRolesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
