"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bridge_get_community_params import BridgeGetCommunityParams
globals()['BridgeGetCommunityParams'] = BridgeGetCommunityParams
from openapi_client.model.inline_object import InlineObject


class TestInlineObject(unittest.TestCase):
    """InlineObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject(self):
        """Test InlineObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
