"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_ranked_posts_request_params import GetRankedPostsRequestParams
globals()['GetRankedPostsRequestParams'] = GetRankedPostsRequestParams
from openapi_client.model.get_ranked_posts_request import GetRankedPostsRequest


class TestGetRankedPostsRequest(unittest.TestCase):
    """GetRankedPostsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetRankedPostsRequest(self):
        """Test GetRankedPostsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetRankedPostsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
