"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.profile_metadata_profile import ProfileMetadataProfile
globals()['ProfileMetadataProfile'] = ProfileMetadataProfile
from openapi_client.model.profile_metadata import ProfileMetadata


class TestProfileMetadata(unittest.TestCase):
    """ProfileMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProfileMetadata(self):
        """Test ProfileMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProfileMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
