"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bridge_get_community_context_params import BridgeGetCommunityContextParams
globals()['BridgeGetCommunityContextParams'] = BridgeGetCommunityContextParams
from openapi_client.model.inline_object1 import InlineObject1


class TestInlineObject1(unittest.TestCase):
    """InlineObject1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject1(self):
        """Test InlineObject1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineObject1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
