"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.error_message_error import ErrorMessageError
globals()['ErrorMessageError'] = ErrorMessageError
from openapi_client.model.error_message import ErrorMessage


class TestErrorMessage(unittest.TestCase):
    """ErrorMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorMessage(self):
        """Test ErrorMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
