"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_relationship_between_accounts_request_params import GetRelationshipBetweenAccountsRequestParams
globals()['GetRelationshipBetweenAccountsRequestParams'] = GetRelationshipBetweenAccountsRequestParams
from openapi_client.model.get_relationship_between_accounts_request import GetRelationshipBetweenAccountsRequest


class TestGetRelationshipBetweenAccountsRequest(unittest.TestCase):
    """GetRelationshipBetweenAccountsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetRelationshipBetweenAccountsRequest(self):
        """Test GetRelationshipBetweenAccountsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetRelationshipBetweenAccountsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
