"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_all_subscriptions_request_params import ListAllSubscriptionsRequestParams
globals()['ListAllSubscriptionsRequestParams'] = ListAllSubscriptionsRequestParams
from openapi_client.model.list_all_subscriptions_request import ListAllSubscriptionsRequest


class TestListAllSubscriptionsRequest(unittest.TestCase):
    """ListAllSubscriptionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAllSubscriptionsRequest(self):
        """Test ListAllSubscriptionsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAllSubscriptionsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
