"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.does_user_follow_any_lists_request_params import DoesUserFollowAnyListsRequestParams


class TestDoesUserFollowAnyListsRequestParams(unittest.TestCase):
    """DoesUserFollowAnyListsRequestParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoesUserFollowAnyListsRequestParams(self):
        """Test DoesUserFollowAnyListsRequestParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoesUserFollowAnyListsRequestParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
