"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_account_posts_request_params import GetAccountPostsRequestParams


class TestGetAccountPostsRequestParams(unittest.TestCase):
    """GetAccountPostsRequestParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAccountPostsRequestParams(self):
        """Test GetAccountPostsRequestParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAccountPostsRequestParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
