"""
    Hivemind OpenAPI Specification

    An OpenAPI specification for Hivemind  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.community_context_request_all_of_params import CommunityContextRequestAllOfParams


class TestCommunityContextRequestAllOfParams(unittest.TestCase):
    """CommunityContextRequestAllOfParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommunityContextRequestAllOfParams(self):
        """Test CommunityContextRequestAllOfParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommunityContextRequestAllOfParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
